# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/bkd/git/kdFileFinder\kdFileFinder\script_manager.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(605, 463)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_add_script = QtWidgets.QPushButton(Dialog)
        self.pb_add_script.setObjectName("pb_add_script")
        self.horizontalLayout.addWidget(self.pb_add_script)
        self.pb_edit_script = QtWidgets.QPushButton(Dialog)
        self.pb_edit_script.setObjectName("pb_edit_script")
        self.horizontalLayout.addWidget(self.pb_edit_script)
        self.pb_delete_script = QtWidgets.QPushButton(Dialog)
        self.pb_delete_script.setObjectName("pb_delete_script")
        self.horizontalLayout.addWidget(self.pb_delete_script)
        self.pb_find_script = QtWidgets.QPushButton(Dialog)
        self.pb_find_script.setObjectName("pb_find_script")
        self.horizontalLayout.addWidget(self.pb_find_script)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.formLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.fl_search = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.fl_search.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.fl_search.setContentsMargins(0, 0, 0, 0)
        self.fl_search.setObjectName("fl_search")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_5.setLineWidth(1)
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.fl_search.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_5)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.fl_search.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.fl_search.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.fl_search.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.formLayoutWidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.fl_search.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.plainTextEdit)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.fl_search.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.radioButton = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.fl_search.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.fl_search.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.radioButton_2)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.fl_search.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.fl_search.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.lv_script = QtWidgets.QListWidget(self.splitter)
        self.lv_script.setAutoFillBackground(False)
        self.lv_script.setStyleSheet("")
        self.lv_script.setObjectName("lv_script")
        self.textBrowser = QtWidgets.QTextBrowser(self.splitter)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.splitter)
        self.verticalLayout.setStretch(0, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "脚本管理"))
        self.pb_add_script.setText(_translate("Dialog", "新增"))
        self.pb_edit_script.setText(_translate("Dialog", "编辑"))
        self.pb_delete_script.setText(_translate("Dialog", "删除"))
        self.pb_find_script.setText(_translate("Dialog", "查询"))
        self.label_5.setText(_translate("Dialog", "搜索"))
        self.label.setText(_translate("Dialog", "右键名称"))
        self.label_2.setText(_translate("Dialog", "脚本路径"))
        self.label_3.setText(_translate("Dialog", "应用于"))
        self.radioButton.setText(_translate("Dialog", "选中项"))
        self.radioButton_2.setText(_translate("Dialog", "指定文件类型"))
        self.label_4.setText(_translate("Dialog", "文件类型"))


